### ISSUE TITLE
Handle high frequent event fireing

### ISSUE THREAD

**Issue by kamataryo** [tilecloud/mbgl-gesture-handling#2]
Decimating too frequent event is very effective to improve UX.

**Comment by miya0001** [comment]
## The 1st one.
https://github.com/tilecloud/mbgl-gesture-handling/blob/master/mbgl-gesture-handling.js#L58-L70

It is used for hide help immediately if user do wheel with [alt] key.
The reason we need this event is if help container will be displayed, wheel event on map won't be fired because help container exists on the map container.

## The 2nd
https://github.com/tilecloud/mbgl-gesture-handling/blob/master/mbgl-gesture-handling.js#L72-L78

It will be fired if user do wheel.
The help container will be hide, this event will be fired after 1st event.

The 3rd and 4th events are needed for similar reason.

**Comment by kamataryo** [comment]
Oh, it's not about the types of event, but the frequency.
<img width="665" alt="Screenshot 2019-04-08 02 11 56" src="https://user-images.githubusercontent.com/6292312/55687274-1b5c7c80-59a6-11e9-82c8-35d342ac82ee.png">

**Comment by miya0001** [comment]
It could be improved on https://github.com/tilecloud/mbgl-gesture-handling/commit/a54a5a8536eef53c31d27168c28a40710cdca98b
